version: '3.7'

services:
  db:
    container_name: test_db
    build: .
    image: postgres:12
    restart: always
    env_file: .env
    ports:
      - 5433:5432
    volumes:
      - ./data:/var/lib/postgresql/data
    
  redis:
   image: redis:5
   ports:
     - 6379:6379
   env_file: .env
   volumes:
     - ./myredis/conf:/usr/local/etc/redis