version: '3.1'

services:

  nginx:
    build: ./nginx
    ports:
      - 80:80
    depends_on:
      - web
    volumes:
      - ./static/:/code/static/
      - ./media/:/code/media/

  db:
    image: postgres:14
    restart: always
    ports:
      - "5433:5432"
    volumes:
      - ./pgdb/:/var/lib/postgresql/data
    env_file: ./.env

  web:
    build: .
    restart: always
    ports:
      - "8000:8000"
    volumes:
      - .:/code
      - ./static/:/code/static/

    depends_on:
      - "db"
    env_file: ./.env
    environment:
      - VIRTUAL_HOST=localhost
      - VIRTUAL_PORT=8000
      - HTTP_PORT=8000

  redis:
    image: redis
    ports:
      - 6379:6379
    restart: always

  chromedriver:
    image: selenium/standalone-chrome
    shm_size: 256m
    ports:
      - "4444:4444"

  celery:
    build:
      context: .
      dockerfile: celery.dockerfile
    restart: always
    command: celery -A app worker --beat --scheduler django --loglevel=info
    volumes:
      - .:/code
    depends_on:
      - "db"
      - "redis"
    env_file: ./.env
