# Generated by Django 4.1.7 on 2023-04-13 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='addinstagram',
            old_name='following',
            new_name='follow',
        ),
    ]
