# Generated by Django 4.1.7 on 2023-04-13 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rename_following_addinstagram_follow'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addinstagram',
            name='follow',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='addinstagram',
            name='follower',
            field=models.CharField(max_length=255),
        ),
    ]
